default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/fredit_development

test:
  <<: *default
  database: db/fredit_test

production:
  <<: *default
  database: db/fredit_production
